server:
  port: 8888


spring:
  application:
    name: ieum
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/ieum?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate.jdbc.time_zone: Asia/Seoul
      show-sql: true
    driver-class-name: com.mysql.cj.jdbc.Driver







